-- Insert sample data for inventory
INSERT INTO inventory (product_id, available_quantity, reserved_quantity, version, created_at, last_updated_at) VALUES
(1, 100, 0, 0, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()), -- Laptop Pro X
(2, 50, 0, 0, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),  -- The Great Novel
(3, 200, 0, 0, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()), -- Summer T-Shirt
(4, 75, 0, 0, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()),  -- Smartphone Ultra
(5, 120, 0, 0, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP()); -- Cookbook Basics

-- Insert sample data for inventory_logs (optional, can be generated by service operations)
-- INSERT INTO inventory_logs (product_id, change_type, quantity_change, new_quantity, order_id, timestamp) VALUES
-- (1, 'INITIAL_STOCK', 100, 100, NULL, CURRENT_TIMESTAMP());